services:
  app:
    image: socialcredit
    container_name: socialcredit
    ports:
      - 5000:5000
    env_file: .env
    command: "flask db upgrade && gunicorn app:app --bind 0.0.0.0:5000 --workers 4 --threads 4 --timeout 0"